# 一、Anaconda简介
#### 1.Anaconda 是Python 的一个开源发行版本，已经预装了很多第三方库，比较方便。
#### 2.可以用conda install 来安装第3方库
#### 3.安装地址：www.continuum.io/downloads
> 安装完Anaconda，就相当于安装了Python、IPython、集成开发环境Spyder、一些包等等

# 二、Numpy简介
>是n维的数组对象，叫做ndarray.

#### 1.基本用法

In [1]:
import numpy as np
data1=[1,2,3,4,5]
array1=np.array(data1)
array1

array([1, 2, 3, 4, 5])

In [2]:
data2=[[1,3,4],[2,5,6]]
array2=np.array(data2)
array2

array([[1, 3, 4],
       [2, 5, 6]])

In [3]:
array2.dtype

dtype('int64')

In [4]:
array1.astype('str')

array(['1', '2', '3', '4', '5'],
      dtype='<U21')

In [5]:
array1+1

array([2, 3, 4, 5, 6])

In [6]:
array1*array1

array([ 1,  4,  9, 16, 25])

In [7]:
array1*2

array([ 2,  4,  6,  8, 10])

#### 2. array数组内的元素访问

In [8]:
array1

array([1, 2, 3, 4, 5])

In [9]:
array1[2]

3

In [10]:
array1[-2:]

array([4, 5])

In [11]:
array1[1]=0

In [12]:
array1

array([1, 0, 3, 4, 5])

In [13]:
array2

array([[1, 3, 4],
       [2, 5, 6]])

In [14]:
array2[0]

array([1, 3, 4])

In [15]:
array2[0][1]

3

In [16]:
array2.T     #矩阵转置

array([[1, 2],
       [3, 5],
       [4, 6]])

# 三、关于Pandas
## Pandas是python的一个数据分析包,是做数据分析的得力工具。
#### Series：一维数组
#### DataFrame：二维的表格型数据结构

## 1.Pandas中的数据结构 
####  Series：一维数组

In [181]:
from pandas import Series
X = Series(['a',2,'螃蟹'],index=[4,5,6])  #一个系列允许存放多种数据，索引也可以省略

In [182]:
X

4     a
5     2
6    螃蟹
dtype: object

In [183]:
X[6]

'螃蟹'

In [184]:
from pandas import Series
A=Series([1,2,3])  #定义系列的时候，数据类型不限
print(A)

0    1
1    2
2    3
dtype: int64


In [185]:
from pandas import Series
A=Series([1,2,3],index=[1,2,3])#可自定义索引，如：123；ABCD等
print(A)

1    1
2    2
3    3
dtype: int64


In [186]:
from pandas import Series
A=Series([1,2,3],index=['A','B','C'])
print(A)

A    1
B    2
C    3
dtype: int64


In [187]:
#注意：容易犯的错误
from pandas import Series
A=Series([1,2,3],index=[A,B,C])
print(A)

ValueError: all arrays must be same length

In [188]:
from pandas import Series
A=Series([14,26,31])
print(A)
print( A[1])     #系类的位置从0开始的，第一个数从0开始计数
print( A[5])     #超出index的总长度会报错

0    14
1    26
2    31
dtype: int64
26


KeyError: 5

In [189]:
from pandas import Series
A=Series([14,26,31],index=['first','second','third'])
print(A)
print(A['second'])#如果设置了index参数，也可通过参数来访问系列值

first     14
second    26
third     31
dtype: int64
26


In [190]:
#执行下面的代码看看运行结果:
from pandas import Series
#可以混合定义一个序列
x = Series(['a', True, 1], index=['first', 'second', 'third']);

In [191]:
x.index

Index(['first', 'second', 'third'], dtype='object')

In [192]:
x.values

array(['a', True, 1], dtype=object)

In [193]:
#根据索引号访问
x[1]

True

In [194]:
#根据i索引名访问
x['second']

True

In [195]:
#不能越界访问
x[3]

IndexError: index out of bounds

In [196]:
#不能追加单个元素
x.append('2') 

SyntaxError: invalid character in identifier (<ipython-input-196-dbc591a26a1e>, line 2)

In [197]:
#追加一个序列
n = Series(['2'])
x.append(n)

first        a
second    True
third        1
0            2
dtype: object

In [198]:
x

first        a
second    True
third        1
dtype: object

In [199]:
#需要使用一个变量来承载变化，即x.append(n)返回的是一个新序列
x = x.append(n)
x

first        a
second    True
third        1
0            2
dtype: object

In [200]:
#判断值是否存在,数字和逻辑型(True\False)是不需要加引号的
2 in x.values
'2' in x.values

True

In [201]:
#切片
x[1:3]

second    True
third        1
dtype: object

In [202]:
#定位获取，这个方法经常用于随机抽样
x[[0, 2, 1]]

first        a
third        1
second    True
dtype: object

In [203]:
#根据index删除
x.drop(0)

first        a
second    True
third        1
dtype: object

In [204]:
x

first        a
second    True
third        1
0            2
dtype: object

In [205]:
x.drop('first')

second    True
third        1
0            2
dtype: object

In [206]:

y=Series(['a',2,True],index=['a','b','c'])
y.drop('c')   #索引名

a    a
b    2
dtype: object

In [207]:
z=Series(['a',2,True])
z.drop(2)  #索引号

0    a
1    2
dtype: object

In [208]:
x

first        a
second    True
third        1
0            2
dtype: object

In [209]:
x.index[3] #从索引号返回索引名

0

In [210]:
#根据位置删除,返回新的序列
x.drop(x.index[3])

first        a
second    True
third        1
dtype: object

In [211]:
x.values

array(['a', True, 1, '2'], dtype=object)

In [212]:
'2'!=x.values

array([ True,  True,  True, False], dtype=bool)

In [213]:
#根据值删除,显示不等于2的值的序列,也就是删除2,返回新序列
x['2'!=x.values]

first        a
second    True
third        1
dtype: object

In [214]:
x.index['2'!=x.values]

Index(['first', 'second', 'third'], dtype='object')

In [215]:
#通过值访问序列号index
x.index[x.values=='a']

Index(['first'], dtype='object')

In [216]:
x

first        a
second    True
third        1
0            2
dtype: object

In [217]:
x[0]='cc'
x

first        a
second    True
third        1
0           cc
dtype: object

In [218]:
x[x.index[x.values=='a']]='aa'
x

first       aa
second    True
third        1
0           cc
dtype: object

In [220]:
x = Series(['a', True, 1], index=['first', 'second', 'third'])
n = Series(['2'])
x=x.append(n)
x

first        a
second    True
third        1
0            2
dtype: object

In [221]:
#修改series中的index：可以通过赋值更改，也可以通过reindex()方法
x.index=[0,1,2,3]
x

0       a
1    True
2       1
3       2
dtype: object

In [222]:
y=x.reindex([0,1,2,'d'])
y

0       a
1    True
2       1
d     NaN
dtype: object

In [223]:
y=x.reindex([0,1,2,'d'],fill_value=0)
y

0       a
1    True
2       1
d       0
dtype: object

In [225]:
#可将字典转化为Series
s=Series({'a':1,'b':2,'c':3})
s

a    1
b    2
c    3
dtype: int64

In [226]:
#重排序
#Series 的 sort_index(ascending=True) 方法可以对 index 进行排序操作，
#ascending 参数用于控制升序或降序，默认为升序。也可使用reindex()方法来重排序。
s.sort_index(ascending=False)

c    3
b    2
a    1
dtype: int64

In [227]:

obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [228]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [229]:
#使用reindex()方法来重排序
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [230]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [231]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

##  总结：Series对象本质上是一个NumPy的数组，因此NumPy的数组处理函数可以直接对Series进行处理。但是Series除了可以使用位置作为下标存取元素之外，还可以使用标签下标存取元素，这一点和字典相似。每个Series对象实际上都由两个数组组成：
## index: 它是从NumPy数组继承的Index对象，保存标签信息。
## values: 保存值的NumPy数组。
## 注意三点：
> 1. Series是一种类似于一维数组（数组：ndarray）的对象
> 2. 它的数据类型没有限制（各种NumPy数据类型）
> 3. 它有索引，把索引当做数据的标签（key）看待，这样就类似字典了（只是类似，实质上是数组)
> 4. Series同时具有数组和字典的功能，因此它也支持一些字典的方法。


# DataFrame：二维的表格型数据结构

## DataFrame：是用于存储多行和多列的数据集合，是series的容器。
		Dataframe(columnsMap)

In [232]:
from pandas import DataFrame
df=DataFrame({'age':Series([26,29,24]),'name':Series(['Ken','Jerry','Ben'])},index=[0,1,2])
df

age   name
0   26    Ken
1   29  Jerry
2   24    Ben

# DataFrame的访问方法：
### 访问列---->   变量名[列名]------------> 访问对应的列------->如df['name']
### 访问行---->   变量名[n：m]-----------> 访问n行到m-1行的数据------->如df[2:3]
### 访问行和列->变量名.iloc[n1:n2,m1:m2]	---->  访问n1到(n2-1)行，m1到(m2-1)列的数据----->如df.iloc[0:3,0:2]
### 访问位置---> 变量名.at[行名,列名]-----------> 访问 (行名,列名)位置的数据-------->如df.at[1,'name']

In [233]:
A=df['age']   #获取age的列值,也可以写成df.age
print(A)

0    26
1    29
2    24
Name: age, dtype: int64


In [234]:
B=df[1:3] #获取序号是第一行的值（其实是第二行，从0开始的）
print(B)

   age   name
1   29  Jerry
2   24    Ben


In [235]:
C=df.iloc[0:2,0:2] #获取第0行到1行（不含）与第0列到2列（不含）交叉值
print(C)

   age   name
0   26    Ken
1   29  Jerry


In [236]:
D=df.at[0,'name']  #获取第0行与name列的交叉值
print(D)

Ken


In [237]:
from pandas import DataFrame
df1 = DataFrame({
    'age': [21, 22, 23], 
    'name': ['KEN', 'John', 'JIMI']});

In [238]:
df2 = DataFrame(data={
    'age': [21, 22, 23], 
    'name': ['KEN', 'John', 'JIMI']}, 
    index=['first', 'second', 'third']);

In [239]:
df1

age  name
0   21   KEN
1   22  John
2   23  JIMI

In [240]:
df2

age  name
first    21   KEN
second   22  John
third    23  JIMI

In [242]:
df2.at['first','age']

21

In [243]:
#修改列名
df2.columns=['age2', 'name2']
df2

age2 name2
first     21   KEN
second    22  John
third     23  JIMI

In [244]:
#修改行索引
df2.index = range(1,4)
df2

age2 name2
1    21   KEN
2    22  John
3    23  JIMI

In [245]:
df

age   name
0   26    Ken
1   29  Jerry
2   24    Ben

In [143]:
#根据行索引删除
df.drop(1, axis=0) # axis=0是表示行轴,也可以省略


age2  name2
2    29  Jerry
3    24    Ben

In [145]:
#修改行索引
df.index = ['a','b','c']
df

age2  name2
a    26    Ken
b    29  Jerry
c    24    Ben

In [147]:
#根据行索引删除
df.drop('a', axis=0) # axis=0是表示行轴,也可以省略


age2  name2
b    29  Jerry
c    24    Ben

In [148]:
#根据列名进行删除
df.drop('age2', axis=1)  # axis=1表示列轴，不可省略

name2
a    Ken
b  Jerry
c    Ben

In [149]:
df

age2  name2
a    26    Ken
b    29  Jerry
c    24    Ben

In [150]:
#第二种删除列的方法
del df['age2']

In [151]:
df

name2
a    Ken
b  Jerry
c    Ben

In [152]:
#增加列
df['newColumn']= [2, 4, 6] 

In [153]:
df

name2  newColumn
a    Ken          2
b  Jerry          4
c    Ben          6

In [154]:
#增加行，注意这种方法，效率比较低
df.loc[len(df)] = [ 24,"KENKEN"]

In [155]:
df

name2 newColumn
a    Ken         2
b  Jerry         4
c    Ben         6
3     24    KENKEN

In [157]:
#增加行的办法可以通过合并两个datafram来解决。如：
df = DataFrame([[1, 2], [3, 4]], columns=list('AB'))
df2 = DataFrame([[5, 6], [7, 8]], columns=list('AB'))
df.append(df2)  #仅把两个datafram“叠”起来了，没有修改df2的index

A  B
0  1  2
1  3  4
0  5  6
1  7  8

In [158]:
df.append(df2, ignore_index=True) #修改index，对df2重新索引了

A  B
0  1  2
1  3  4
2  5  6
3  7  8

# 三、数据导入 
## 数据存在的形式多样，有文件（csv、excel、txt）和数据库（mysql、access、sql server）等形式。
## 1.导入txt文件：
#### reda_table(file,names=[列名1，列名2，..],sep="",…)
####			file: 文件路径文件名
####			names：列名，默认为文件中的第一行作为列名
####			sep：分隔符，默认为空，表示默认导入为一列

In [159]:
import pandas as pd
df = pd.read_table('data/rz.txt',sep='\t')
df.head()

/anaconda3/envs/course_py35/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead.
  


学号        班级  姓名 性别  英语  体育  军训  数分  高代  解几
0  2308024241  23080242  成龙  男  76  78  77  40  23  60
1  2308024244  23080242  周怡  女  66  91  75  47  47  44
2  2308024251  23080242  张波  男  85  81  75  45  45  60
3  2308024249  23080242  朱浩  男  65  50  80  72  62  71
4  2308024219  23080242  封印  女  73  88  92  61  47  46

In [160]:
df = pd.read_csv('data/rz.csv',sep=',')
df.head()

学号        班级  姓名 性别  英语  体育  军训  数分  高代  解几
0  2308024241  23080242  成龙  男  76  78  77  40  23  60
1  2308024244  23080242  周怡  女  66  91  75  47  47  44
2  2308024251  23080242  张波  男  85  81  75  45  45  60
3  2308024249  23080242  朱浩  男  65  50  80  72  62  71
4  2308024219  23080242  封印  女  73  88  92  61  47  46

In [161]:
df = pd.read_excel('data/i_nuc.xls',sheetname='Sheet1')
df.head()

/anaconda3/envs/course_py35/lib/python3.6/site-packages/pandas/util/_decorators.py:188: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)


日期  优盘  电子表  电脑支架  插座    电池  音箱  鼠标  usb数据线  手机充电线  键盘
0 2017-01-01  17    6     8  24  13.0  13  18      10     10  27
1 2017-01-02  11   15    14  13   9.0  10  19      13     14  13
2 2017-01-03  10    8    12  13   8.0   3   7      11     10   9
3 2017-01-04   9    6     6   3  10.0   9   9      13     14  13
4 2017-01-05   4   10    13   8  12.0  10  17      11     13  14

# 四、数据导出 
## 1.导出csv文件

In [162]:
from pandas import DataFrame
from pandas import Series
df = DataFrame(
{'age':Series([26,85,64]),'name':Series(['Ben','John','Jerry'])})
print(df)

   age   name
0   26    Ben
1   85   John
2   64  Jerry


In [163]:
df.to_csv('data/01.csv')                 #默认带上index
df.to_csv('data/02.csv',index=False)     #无index

## 2.导出excel文件


In [164]:
from pandas import DataFrame
from pandas import Series
df = DataFrame(
{'age':Series([26,85,64]),
'name':Series(['Ben','John','Jerry'])})
df.to_excel('data/01.xlsx')               #默认带上index
df.to_excel('data/02.xlsx',index=False)   #无index